Storage:
  path: "/mnt/c/Users/witol/go/syncbrok/temp/"
Queues: 
  simple :
    urls :
      - "http://localhost:10000/msg"
  test:
    urls :
        - "http://localhost:20000/"
  whatever:
    urls :
      - "http://localhost:10000/msg"
